config/routes.rb
Rails.application.routes.draw do
  root to: 'cocktails#index'
  resources :cocktails, only: %i[index show new create] do
    resources :doses, only: %i[create destroy]
    resources :reviews, only: %i[create destroy]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :name, uniqueness: true

  mount_uploader :photo, PhotoUploader
  validates :photo, presence: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates_uniqueness_of :cocktail_id, scope: :ingredient_id
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, through: :doses
  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :cocktail
  validates :content, :author, :rating, presence: true
  validates :rating, numericality: true, inclusion: { in: 1..5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @dose = Dose.new
    @review = Review.new
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktails_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail), notice: 'Congratulations, your cocktail was successfully created.'
    else
      render :new
    end
  end

  private

  def cocktails_params
    params.require(:cocktail).permit(:name, :photo)
  end

end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :set_cocktail

  def create
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      @review = Review.new
      render 'cocktails/show'
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end

  def set_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_cocktail

    def create
      @review = Review.new(review_params)
      @review.cocktail = @cocktail
      if @review.save
        redirect_to cocktail_path(@cocktail)
      else
        @dose = Dose.new
        render 'cocktails/show'
      end
    end

    def destroy
      @review = Review.find(params[:id])
      @review.destroy
      redirect_to cocktail_path(@cocktail)
    end

    private

    def review_params
      params.require(:review).permit(:content, :author, :rating)
    end

    def set_cocktail
      @cocktail = Cocktail.find(params[:cocktail_id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/cocktails/_dose-form.html.erb
<%= simple_form_for [@cocktail, @dose] do |f| %>
  <% if @dose.errors.any? %>
    <div class="alert alert-danger">
      <h4>Warning! You have some errors:</h4>
        <ul>
          <% @dose.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
    </div>
  <% end %>

  <div class="form-inputs">
    <%= f.input :description, label: 'Quantity' %>
    <%= f.association :ingredient %>
  </div>

  <div class="form-actions btn-primary btn">
    <%= f.button :submit, 'Add ingredient' %>
  </div>

<% end %>

app/views/cocktails/_form.html.erb
<%= simple_form_for @cocktail do |f| %>
  <% if @cocktail.errors.any? %>
    <div class="alert alert-danger">
      <h4>Warning! You have some errors:</h4>
        <ul>
          <% @cocktail.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
    </div>
  <% end %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>
  </div>

  <div class="form-actions btn-primary btn">
    <%= f.button :submit %>
  </div>

<% end %>

app/views/cocktails/_review-form.html.erb
<%= simple_form_for [@cocktail, @review] do |f| %>
  <% if @review.errors.any? %>
    <div class="alert alert-danger">
      <h4>Warning! You have some errors:</h4>
        <ul>
          <% @review.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
    </div>
  <% end %>

  <div class="form-inputs">
    <%= f.input :content, label: 'Your opinion' %>
    <%= f.input :author, label: 'Your name' %>
    <%= f.input :rating %>
  </div>

  <div class="form-actions btn-primary btn">
    <%= f.button :submit, 'Add review' %>
  </div>

<% end %>

app/views/cocktails/index.html.erb
<h1>Discover brand new cocktails</h1>

<div class="cards">
  <% @cocktails.each do |c| %>
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path c.photo.url %>')">
    <%= link_to(c.name, cocktail_path(c)) %>
  </div>
  <% end %>
</div>

app/views/cocktails/new.html.erb
<div class="cocktail-container">
  <h1>Add a new cocktail</h1>
    <%= render 'form' %>
</div>

app/views/cocktails/show.html.erb
<%= notice %>
<div class="card-header" style="background-image: url('<%= cl_image_path @cocktail.photo.url %>')">
  <%= @cocktail.name %>
</div>

<div class="show-container">

  <div class="list-container">
    <ul class="list-group">
      <% @cocktail.doses.each do |dose| %>
        <li class="list-group-item">
          <%= dose.description %> of <%= dose.ingredient.name %>
          <%= link_to cocktail_dose_path(@cocktail, dose), method: :delete, data: {confirm: "Are you sure?"} do %>
              <i class="far fa-trash-alt"></i>
          <% end %>
        </li>
      <% end %>
    </ul>

    <%= render 'cocktails/review-form' %>
  </div>

  <div class="review-container">
    <ul class="list-group">
      <% @cocktail.reviews.each do |review| %>
        <li class="list-group-item">
          <%= '⭐️' * review.rating %> <%= review.content %> written by <%= review.author %>
          <%= link_to cocktail_review_path(@cocktail, review), method: :delete, data: {confirm: "Are you sure?"} do %>
              <i class="far fa-trash-alt"></i>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>

  <div class="form-container">
    <h5>Add a new ingredient</h2>
    <%= render 'cocktails/dose-form' %>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MisterCocktail</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <nav class="navbar navbar-expand-sm navbar-light navbar-lewagon">
      <%= link_to cocktails_path, class: "navbar-brand" do %>
        <%= image_tag "https://image.flaticon.com/icons/svg/135/135754.svg" %>
      <% end %>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>


      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to "🍸 New Cocktail", new_cocktail_path, class: "nav-link" %>
          </li>
        </ul>
      </div>
    </nav>

    <main>
      <div class="main-container">
        <%= yield %>
      </div>
    </main>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->
  </body>
</html>